{"timestamp":"2025-10-25T18:27:01.665984Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-25T18:27:01.666676Z","level":"info","event":"Filling up the DagBag from /home/mural/log-analysis-automation/airflow/dags/log_analyzer_dag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-25T18:27:01.703272Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.703391Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.703485Z","level":"info","event":"Current task name:log_task","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.703518Z","level":"info","event":"Dag name:log_dag","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.703924Z","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":78}
{"timestamp":"2025-10-25T18:27:01.704449Z","level":"info","event":"Running command: ['/usr/bin/bash', '-c', 'sh /home/mural/log-analysis-automation/wrapperScript.sh ']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":88}
{"timestamp":"2025-10-25T18:27:01.708374Z","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":99}
{"timestamp":"2025-10-25T18:27:01.729240Z","level":"info","event":"Traceback (most recent call last):","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":106}
{"timestamp":"2025-10-25T18:27:01.729355Z","level":"info","event":"  File \"/home/mural/log-analysis-automation/log_analyzer.py\", line 5, in <module>","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":106}
{"timestamp":"2025-10-25T18:27:01.729388Z","level":"info","event":"    import psycopg2 # postgresql client library (connect, cursors, transactions)","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":106}
{"timestamp":"2025-10-25T18:27:01.729407Z","level":"info","event":"    ^^^^^^^^^^^^^^^","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":106}
{"timestamp":"2025-10-25T18:27:01.729424Z","level":"info","event":"ModuleNotFoundError: No module named 'psycopg2'","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":106}
{"timestamp":"2025-10-25T18:27:01.732455Z","level":"info","event":"Command exited with return code 1","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":110}
{"timestamp":"2025-10-25T18:27:01.732881Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/mural/log-analysis-automation/venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/mural/log-analysis-automation/venv/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/mural/log-analysis-automation/venv/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/mural/log-analysis-automation/venv/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-25T18:27:01.733734Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.733994Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.734038Z","level":"info","event":"Task:<Task(BashOperator): log_task>","logger":"task.stdout"}
{"timestamp":"2025-10-25T18:27:01.734060Z","level":"info","event":"Failure caused by Bash command failed. The command returned a non-zero exit code 1.","logger":"task.stdout"}
